---
- hosts: all
  gather_facts: no
  tasks:
    - name: print group_vars
      debug:
        var: vars_by_group_vars

    - name: print host vars
      debug:
        var: vars_by_host_vars

    - name: vars_by_group_vars + vars_by_host_vars
      set_fact:
        cal_result: "{{ vars_by_group_vars + vars_by_host_vars }}"

    - name: print cal_vars
      debug:
        var: cal_result
