---
- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install nginx
  yum:
    name: nginx
    state: latest

- template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/backend.conf

- systemd:
    name: nginx
    state: started
    enabled: yes
