---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: get process list
      shell: |
        set -o pipefail
        ps -ef |grep -v grep
      changed_when: no
      register: ret

    - debug: var=ret
