---
- name: using galaxy
  hosts: node-1
  tasks:
    - import_role:
        name: irixjp.role_example_hello

    - import_role:
        name: irixjp.role_example_uptime

    - name: get locale
      sample_get_locale:
      register: ret

    - debug: var=ret
