---
- hosts: node-1
  gather_facts: no
  tasks:
    - name: exec hostname command
      shell: hostname
      register: ret

    - name: print ret
      debug:
        var: ret

    - name: create a directory
      file:
        path: /tmp/testdir
        state: directory
        mode: '0755'
      register: ret

    - name: print ret
      debug:
        var: ret
